server:
  type: simple
  applicationContextPath: /academico
  adminContextPath: /admin
  connector:
    type: http
    port: 8080

logging:
  level: INFO
  loggers:
    org.hibernate: WARN
    io.dropwizard: INFO
    br.ufal.ic: TRACE
    org.eclipse.jetty.servlets: INFO
  appenders:
    - type: console

database:
  # the name of your JDBC driver
  driverClass: org.h2.Driver
  user: sa
  password:
  url: jdbc:h2:~/test
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: update